### ISSUE TITLE
Importing save files (any type, sav, dsv) causes the emulator to reset. This stops us from using saves.

### ISSUE THREAD

**Issue by BypassGoGuardianPLS** [44670/desmume-wasm#22] opened 2022-01-27 03:19 UTC
Dsv is the save file used by the emulator. i may have to check the info between a real dsv and the exported dsv for any differences in formatting.

**Comment by 44670** [comment] 2022-02-02 04:26
Duplicate of #13

**Closed by 44670** 2022-02-02 04:26 UTC
