### ISSUE TITLE
Ideas for the emulator

### ISSUE THREAD

**Issue by skygames23** [44670/desmume-wasm#6] opened 2021-11-06 21:49 UTC
-Speed button
-Possibility of changing the size of the buttons
-Possibility of using cheats

**Comment by RunTheCoins** [comment] 2021-11-09 15:53
also It would be cool if you can change the size of the screen for like a widescreen cheat code, as I feel as it is small.

**Comment by EBmang101** [comment] 2021-11-24 19:07
I would love there to be skins so we know which button to press I also want the skins for customization 😂 but great Emulator! Runs so smooth on a app browser called opera Gx

**Comment by 44670** [comment] 2022-02-23 04:45
Duplicate of #12 #21

**Closed by 44670** 2022-02-23 04:45 UTC
