### ISSUE TITLE
Change the lenguage of games

### ISSUE THREAD

**Issue by adrix0202** [44670/desmume-wasm#82] opened 2022-08-02 18:02 UTC
Can you add a version where you can choose the language of multi-language games? It would help me a lot, Because the games are automatically put in English, I do not speak much English and there are words that I do not understand, and it is a problem for me. It would help if you fix it.
Thanks.

**Comment by 44670** [comment] 2022-08-02 23:28
Duplicate of #74

**Closed by 44670** 2022-08-02 23:28 UTC
