### ISSUE TITLE
Cheat mode was disappeared

### ISSUE THREAD

**Issue by loDUKEol** [44670/desmume-wasm#111] opened 2022-10-10 02:15 UTC
I dont know where is the cheat mode
its disappeared
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by 44670** [comment] 2022-10-10 06:33
Duplicate of #105

**Closed by 44670** 2022-10-10 06:33 UTC
