### ISSUE TITLE
DS Emulator in a Nutshell

### ISSUE THREAD

**Issue by ZackandHack** [44670/desmume-wasm#29] opened 2022-02-15 02:44 UTC
So basically I played this DS browser emulator and oh my goodness is this good as playing it is possible now rather then the old buggy DS browser emulators and I use a Chromebook to play them (Mostly a School Chromebook) I was noticing some drop in fps as I play Animal Crossing Wild World and when Im in a building the fps goes by 50 to even 60 (On a school Chromebook my I remind you) and when I leave a building I happen to notice the frames go down to 30-40 fps and while I do understand why this is the case, A idea came to me that why not add a thing in which you get to control your fps as seen in other emulators, this alone would make this the best DS browser emulator period, Also I saw there is no Wi-Fi connection and this one I can understand why you could not add but if it is possible I wanted to know if you could add Wi-Fi connection, I know all of this sounds a lot but honestly I never had once seen such a good DS emulator like this and I was wondering if you could make it even better. :D

**Comment by 44670** [comment] 2022-02-17 04:29
You can limit the fps to 30 by selecting "power-save mode" in the menu.

**Comment by ZackandHack** [comment] 2022-02-17 20:19
But why would I limit it to 30 as I would want it to run as fast as possible

**Comment by 44670** [comment] 2022-02-18 00:53
Because your screen is (most likely) running at 60fps. Loss of synchronization with the screen refresh cycle can lead to unstable delay during the gameplay. 30/60fps are two easy-to-implement options.

**Comment by ZackandHack** [comment] 2022-02-18 01:46
Thank you for the responds and all I have is one question which is can you add Nintendo Wi-Fi supported for games like Animal Crossing Wild World so I can unlock the next shop in the game and if you cant I was wondering if local multiplayer could work as well

**Comment by 44670** [comment] 2022-02-18 01:48
It's not that easy to support multiplay in the browser, which is a sandbox environment that restricts access to the local network.

**Comment by ZackandHack** [comment] 2022-02-18 01:49
Whatever that being online or local

**Comment by 44670** [comment] 2022-02-18 01:51
It may be possible for playing with other web-based users.

**Comment by ZackandHack** [comment] 2022-02-18 02:41
Does that mean your going to add more support to the DS emulator then :D

An idea I was also thing is Cheat codes

**Comment by 44670** [comment] 2022-02-23 15:01
Duplicate of #21

**Closed by 44670** 2022-02-23 15:01 UTC

**Comment by ZackandHack** [comment] 2022-02-24 01:32
Just a question but do you have any release date when you are updating the emulator :D

**Comment by 44670** [comment] 2022-02-25 07:17
In few weeks, I guess.

**Comment by ZackandHack** [comment] 2022-03-12 21:03
Any update so far

**Comment by ZackandHack** [comment] 2022-03-17 19:56
Hey I was wondering If if you added any BETA features yet

**Comment by 44670** [comment] 2022-03-21 11:45
You can find the new features in 'whats new'.
